title: DGW
logo: https://github.com/dgwalters-1974/portfolio/blob/main/docs/assets/images/DALL%C2%B7E%202024-11-15%2018.11.28%20-%20A%20grayscale%20illustration%20of%20a%20deep%20neural%20network%20schematic%20with%20a%20circular%20layout%2C%20surrounded%20by%20mathematical%20equations%20such%20as%20those%20for%20Support%20Vec.webp
description: text below image
theme: jekyll-theme-minimal
show_downloads: true
